name: Deploy della Documentazione

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4
